---

# Creates the default realm, if it's not already present.

- name: Create the new realm
  ansible.builtin.expect:
    command: /usr/sbin/krb5_newrealm
    responses:
      'Enter KDC database master key:': "{{ vault_kerberos_master_key }}"
      'Re-enter KDC database master key to verify:': "{{ vault_kerberos_master_key }}"
  when: install_krb.changed
  become: true
  no_log: true

- name: Add Kerberos policies
  when: install_krb.changed
  become: true
  block:
    - name: Add default Kerberos policy
      ansible.builtin.command:
        cmd: kadmin.local -q "add_policy -minlength 12 -minclasses 3 default"
    - name: Add hosts Kerberos policy
      ansible.builtin.command:
        cmd: kadmin.local -q "add_policy -minlength 32 -minclasses 3 hosts"
    - name: Add services Kerberos policy
      ansible.builtin.command:
        cmd: kadmin.local -q "add_policy -minlength 32 -minclasses 3 services"

- name: Deploy kadm5.acl template
  ansible.builtin.template:
    src: templates/kadm5.acl.j2
    dest: /etc/krb5kdc/kadm5.acl
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
  notify:
    - "Restart 'krb5-admin-server'"
