---
##
# Manages the principals for the domain that are used for tests.
##

- name: Add Test User Principal
  krb_principal:
    name: 'test'
    password: "{{ lookup('password', '/tmp/justdavis-ansible-test-password chars=ascii_letters,digits,punctuation length=32') }}"
    policy: default
  become: true
  no_log: true

