---
##
# Manages the principals for the domain: creating any that should exist, and 
# (perhaps eventually) deleting any that shouldn't. The passwords used here are
# only the **initial** ones, and should be changed by the account owners ASAP.
#
# For a small domain such as this one, it's easier to manage everything in 
# Ansible like this, as opposed to manually creating the principals. 
##

- name: Add Missing User Principals
  krb_principal:
    name: "{{ item.key }}"
    password: "{{ item.value.initialPassword }}"
    policy: default
    pwexpire: '0 seconds'
  with_dict: "{{ people }}"
  become: true
  no_log: true

- name: Add Missing Host Principals
  krb_principal:
    name: "{{ item }}"
    policy: hosts
  with_items:
    - "host/eddings.{{ domain }}"
  become: true

- name: Add Missing Service Principals
  krb_principal:
    name: "{{ item }}"
    policy: services
  with_items:
    - "host/eddings.{{ domain }}"
  become: true

