---
##
# Manages the principals for the domain that are used for tests.
##

- name: Add Test User Principal
  krb_principal:
    name: "{{ test_username }}"
    password: "{{ test_password }}"
    policy: default
  become: true
  no_log: true

