---
- name: apache-restart
  ansible.builtin.service:
    name: apache2
    state: restarted
  become: true
- name: apache-reload
  ansible.builtin.service:
    name: apache2
    state: reloaded
  become: true
