---

- name: Install PostgreSQL
  ansible.builtin.package:
    name:
      # Install the PostgreSQL server:
      - postgresql
      # Install the PostgreSQL client:
      - postgresql-client
  become: true

- name: Create Database Dump Directory
  ansible.builtin.file:
    path: /var/lib/postgresql/backups
    state: directory
    owner: postgres
    group: postgres
    mode: u=rwx,g=,o=
  become: true

- name: Create Database Dump Service Unit
  ansible.builtin.copy:
    src: postgresql-dumpall.service
    dest: /etc/systemd/system/postgresql-dumpall.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true

  # This will run the dump unit hourly.
- name: Create Database Dump Timer
  ansible.builtin.copy:
    src: postgresql-dumpall.timer
    dest: /etc/systemd/system/postgresql-dumpall.timer
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true

- name: Enable and Start Database Dump Timer
  ansible.builtin.systemd:
    name: postgresql-dumpall.timer
    state: started
    enabled: true
    daemon_reload: true
  become: true
