---

- name: Install PostgreSQL
  ansible.builtin.package:
    name:
      # Install the PostgreSQL server:
      - postgresql
      # Install the PostgreSQL client:
      - postgresql-client
  become: true

- name: Configure PostgreSQL to Listen on localhost and Docker Bridge
  ansible.builtin.lineinfile:
    path: /etc/postgresql/14/main/postgresql.conf
    regexp: '^listen_addresses ='
    line: "listen_addresses = 'localhost,172.17.0.1'"
    backup: false
  become: true
  notify: Restart PostgreSQL

- name: Allow Connections from Docker Bridge in pg_hba.conf
  ansible.builtin.lineinfile:
    path: /etc/postgresql/14/main/pg_hba.conf
    insertafter: '^#.*IPv4 local connections:'
    line: "host    all    all    172.17.0.0/16    md5"
    backup: false
  become: true
  notify: Restart PostgreSQL

- name: Allow PostgreSQL (5432) for Docker Bridge Network
  community.general.ufw:
    rule: allow
    port: '5432'
    proto: tcp
    src: '172.17.0.0/16'

- name: Create the Override Directory for PostgreSQL's Service
  ansible.builtin.file:
    path: /etc/systemd/system/postgresql@14-main.service.d
    state: directory
    mode: '0755'

- name: Create systemd override for PostgreSQL
  ansible.builtin.copy:
    dest: /etc/systemd/system/postgresql@14-main.service.d/override.conf
    content: |
      [Unit]
      After=docker.service docker.socket network-online.target
      Wants=docker.service docker.socket network-online.target
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart PostgreSQL
    - Reload systemd

- name: Create Database Dump Directory
  ansible.builtin.file:
    path: /var/lib/postgresql/backups
    state: directory
    owner: postgres
    group: postgres
    mode: u=rwx,g=,o=
  become: true

- name: Create Database Dump Service Unit
  ansible.builtin.copy:
    src: postgresql-dumpall.service
    dest: /etc/systemd/system/postgresql-dumpall.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true

  # This will run the dump unit hourly.
- name: Create Database Dump Timer
  ansible.builtin.copy:
    src: postgresql-dumpall.timer
    dest: /etc/systemd/system/postgresql-dumpall.timer
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true

- name: Enable and Start Database Dump Timer
  ansible.builtin.systemd:
    name: postgresql-dumpall.timer
    state: started
    enabled: true
    daemon_reload: true
  become: true
