---

- name: Create File Share Directories
  file:
    state: directory
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { path: '/var/fileshares', owner: 'root', group: 'root', mode: 'u=rwx,g=rwx,o=rxt' }
    - { path: "/var/fileshares/{{ domain }}/users", owner: 'root', group: 'root', mode: 'u=rwx,g=rwx,o=rxt' }
    - { path: "/var/fileshares/{{ domain }}/groups", owner: 'root', group: 'root', mode: 'u=rwx,g=rwx,o=rxt' }
    - { path: "/var/fileshares/{{ domain }}/groups/karlanderica", owner: 'karl', group: 'karlanderica', mode: 'u=rwxs,g=rwxs,o=t' }
    - { path: "/var/fileshares/{{ domain }}/groups/sysadmin", owner: 'karl', group: 'administrators_posix', mode: 'u=rwxs,g=rwxs,o=rxst' }
  become: true

- name: Create User Share Directories
  file:
    state: directory
    path: "/var/fileshares/{{ domain }}/users/{{ item.key }}"
    owner: "{{ item.key }}"
    group: "{{ item.key }}"
    mode: u=rwxs,g=rwxs,o=
  with_dict: "{{ people }}"
  become: true

- name: Create Service Principals for Samba Server
  krb_principal:
    name: "cifs/{{ item }}.{{ domain }}"
    policy: services
  become: true
  with_items:
    # Not sure this is needed, since Samba isn't listening on that IP. Doesn't hurt, though.
    - eddings
    # Samba listens on the LAN/VPN-only IP that this resolves to.
    - eddings.karlanderica

- name: Create Service Keytab for Samba Server
  script: "roles/ldap_server/files/add-keytab.sh --principal cifs/{{ item }}.{{ domain }} --keytab /etc/samba/smbd.keytab"
  become: true
  with_items:
    - eddings
    - eddings.karlanderica

- name: Secure Samba Server Keytab
  file:
    path: /etc/samba/smbd.keytab
    state: file
    owner: root
    group: root
    mode: 'u=r,g=r,o='
  become: true
  notify:
    - "Restart 'samba'"

- name: Configure smb.conf
  template:
    src: templates/smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
  notify:
    - "Restart 'samba'"

# Not sure why this is required, since we're not using guest accounts for anything,
# but Samba refuses to start without it.
#
# Reference: <https://github.com/NixOS/nixpkgs/issues/95796>
- name: Check Guest Group Mapping
  command: net groupmap list
  register: command_groupmap_list
  changed_when: false
- name: Map Guest Group
  command: net groupmap add sid=S-1-5-32-546 unixgroup=nogroup type=builtin
  become: true
  when: command_groupmap_list.stdout == ""
