---

- name: Create File Share Directories
  file:
    state: directory
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { path: '/var/fileshares', owner: 'root', group: 'root', mode: 'u=rwx,g=rwx,o=rxt' }
    - { path: "/var/fileshares/{{ domain }}/users", owner: 'root', group: 'root', mode: 'u=rwx,g=rwx,o=rxt' }
    - { path: "/var/fileshares/{{ domain }}/groups", owner: 'root', group: 'root', mode: 'u=rwx,g=rwx,o=rxt' }
    - { path: "/var/fileshares/{{ domain }}/groups/karlanderica", owner: 'karl', group: 'karlanderica', mode: 'u=rwxs,g=rwxs,o=t' }
    - { path: "/var/fileshares/{{ domain }}/groups/sysadmin", owner: 'karl', group: 'administrators_posix', mode: 'u=rwxs,g=rwxs,o=rxst' }
  become: true

- name: Create User Share Directories
  file:
    state: directory
    path: "/var/fileshares/{{ domain }}/users/{{ item.key }}"
    owner: "{{ item.key }}"
    group: "{{ item.key }}"
    mode: u=rwxs,g=rwxs,o=
  with_dict: "{{ people }}"
  become: true

- name: Create Service Principal for Samba Server
  krb_principal:
    name: "cifs/eddings.{{ domain }}"
    policy: services
  become: true

- name: Create Service Keytab for Samba Server
  script: "roles/ldap_server/files/add-keytab.sh --principal cifs/eddings.{{ domain }} --keytab /etc/samba/smbd.keytab"
  become: true

- name: Secure Samba Server Keytab
  file:
    path: /etc/samba/smbd.keytab
    state: file
    owner: root
    group: root
    mode: 'u=r,g=r,o='
  become: true
  notify:
    - "Restart 'samba'"

- name: Configure smb.conf
  template:
    src: templates/smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
  notify:
    - "Restart 'samba'"

