---

- name: Create File Share Directories
  file:
    state: directory
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { path: '/var/fileshares', owner: 'root', group: 'root', mode: 'u=rwx,g=rwx,o=rxt' }
    - { path: "/var/fileshares/{{ domain }}/users", owner: 'root', group: 'root', mode: 'u=rwx,g=rwx,o=rxt' }
    - { path: "/var/fileshares/{{ domain }}/groups", owner: 'root', group: 'root', mode: 'u=rwx,g=rwx,o=rxt' }
    - { path: "/var/fileshares/{{ domain }}/groups/karlanderica", owner: 'karl', group: 'karlanderica', mode: 'u=rwxs,g=rwxs,o=t' }
    - { path: "/var/fileshares/{{ domain }}/groups/sysadmin", owner: 'karl', group: 'administrators_posix', mode: 'u=rwxs,g=rwxs,o=rxst' }
    - { path: "/var/fileshares/{{ domain }}/groups/media", owner: 'root', group: 'media_managers', mode: 'u=rwxs,g=rwxs,o=rxst' }
    - { path: "/var/fileshares/{{ domain }}/groups/media/movies", owner: 'root', group: 'media_managers', mode: 'u=rwxs,g=rwxs,o=rxst' }
    - { path: "/var/fileshares/{{ domain }}/groups/media/tv-shows", owner: 'root', group: 'media_managers', mode: 'u=rwxs,g=rwxs,o=rxst' }
    - { path: "/var/fileshares/{{ domain }}/groups/media/music-videos", owner: 'root', group: 'media_managers', mode: 'u=rwxs,g=rwxs,o=rxst' }
    - { path: "/var/fileshares/{{ domain }}/groups/media/music", owner: 'root', group: 'media_managers', mode: 'u=rwxs,g=rwxs,o=rxst' }
    - { path: "/var/fileshares/{{ domain }}/groups/media/photos", owner: 'root', group: 'media_managers', mode: 'u=rwxs,g=rwxs,o=rxst' }
    - { path: "/var/fileshares/{{ domain }}/groups/media/books", owner: 'root', group: 'media_managers', mode: 'u=rwxs,g=rwxs,o=rxst' }
  become: true

- name: Create User Share Directories
  file:
    state: directory
    path: "/var/fileshares/{{ domain }}/users/{{ item.key }}"
    owner: "{{ item.key }}"
    group: "{{ item.key }}"
    mode: u=rwxs,g=rwxs,o=
  with_dict: "{{ people }}"
  become: true

- name: Create Service Principals for Samba Server
  krb_principal:
    name: "cifs/{{ item }}.{{ domain }}"
    policy: services
  become: true
  with_items:
    # Not sure this is needed, since Samba isn't listening on that IP. Doesn't hurt, though.
    - eddings
    # Samba listens on the LAN/VPN-only IP that this resolves to.
    - eddings.karlanderica

- name: Configure smb.conf
  template:
    src: templates/smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
  notify:
    - "Restart 'samba'"

# Not sure why this is required, since we're not using guest accounts for anything,
# but Samba refuses to start without it.
#
# Reference: <https://github.com/NixOS/nixpkgs/issues/95796>
- name: Check Guest Group Mapping
  command: net groupmap list
  register: command_groupmap_list
  changed_when: false
- name: Map Guest Group
  command: net groupmap add sid=S-1-5-32-546 unixgroup=nogroup type=builtin
  become: true
  when: command_groupmap_list.stdout == ""

- name: Check for Missing Samba Users
  ansible.builtin.command: "pdbedit --list {{ item.key }}"
  no_log: true
  become: true
  changed_when: false
  with_dict: "{{ people }}"
  register: user_lookups
  # This utility returns 0 for successful lookups and 255 for failed ones.
  failed_when: user_lookups.rc not in [0, 255]

- name: Create Missing Samba Users
  ansible.builtin.expect:
    command: "smbpasswd -a {{ item.item.key }}"
    responses:
      "New SMB password:": "{{ item.item.value.initialPassword }}"
      "Retype new SMB password:": "{{ item.item.value.initialPassword }}"
  no_log: true
  become: true
  when: item.stdout.find(item.item.key) == -1
  with_items: "{{ user_lookups.results }}"

- name: Check for Samba Test User
  ansible.builtin.command: "pdbedit --list {{ test_username }}"
  no_log: true
  become: true
  changed_when: false
  register: test_user_lookup
  # This utility seems to always return 255 for some reason.
  failed_when: test_user_lookup.rc not in [0, 255]
  tags: test

- name: Create Samba Test User
  ansible.builtin.expect:
    command: "smbpasswd -a {{ test_username }}"
    responses:
      "New SMB password:": "{{ test_password }}"
      "Retype new SMB password:": "{{ test_password }}"
  no_log: true
  become: true
  when: test_user_lookup.stdout.find(test_username) == -1
  tags: test
