---

- name: Import tasks - install.yml
  ansible.builtin.import_tasks: install.yml
- name: Import tasks - config.yml
  ansible.builtin.import_tasks: config.yml
- name: Import tasks - test.yml
  ansible.builtin.import_tasks: test.yml
  tags: test
