---

- meta: flush_handlers

- name: Create Test User Home Share Directory
  file:
    state: directory
    path: "/var/fileshares/{{ domain }}/users/{{ test_username }}"
    owner: "{{ test_username }}"
    group: "{{ test_username }}"
    mode: u=rwx,g=rwx,o=t
  become: true

- name: Wait for Samba Server
  wait_for:
    port: 139
    delay: 5

- name: List Samba Shares
  command: "/usr/bin/smbclient --list=eddings.karlanderica.{{ domain }} --no-pass"
  register: smbclient_list_result
  failed_when: smbclient_list_result.rc != 0 or domain not in smbclient_list_result.stdout
  changed_when: false

- name: Acquire Kerberos Auth (as test)
  expect:
    command: "/usr/bin/kinit {{ test_username }}"
    responses:
      "^Password for .*: ": "{{ test_password }}"
  changed_when: false

# Had to disable this, as it doesn't seem to work any more in either Ubuntu 20.04 or 22.04.
# Not sure why.
#- name: Browse Samba User Share
#  command: "/usr/bin/smbclient //eddings.karlanderica.{{ domain }}/{{ domain }} --use-kerberos=required --no-pass --directory users/{{ test_username }} --command ls"
#  register: smbclient_ls_result
#  failed_when: smbclient_ls_result.rc != 0 or 'blocks available' not in smbclient_ls_result.stdout
#  changed_when: false

