---

- name: Restart OpenVPN Service
  systemd:
    name: openvpn
    state: restarted
  become: true

- name: Restart VPN IP Forwarding Service
  service:
    name: vpn-ipforwarding
    state: restarted
  become: true

- name: Restart OpenVPN iptables Service
  service:
    name: openvpn-iptables
    state: restarted
  become: true
