---

- name: Install Ansible System Dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-venv
    - python3-virtualenv
    - build-essential
    - python3-dev
    - libpq-dev
    - libssl-dev
    - libffi-dev
  become: true
