---

- name: Install Shared Development Tools
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - openjdk-8-jdk
  become: true

- name: Create AWS Config Directory
  file:
    path: /home/karl/.aws
    state: directory
    owner: karl
    group: karl
    mode: u=rwx,g=rwx,o=rx
  become: true

- name: Create AWS Config
  template:
    src: aws_config.j2
    dest: /home/karl/.aws/config
    owner: karl
    group: karl
    mode: u=rw,g=,o=
  become: true

- name: Create AWS Credentials
  template:
    src: aws_credentials.j2
    dest: /home/karl/.aws/credentials
    owner: karl
    group: karl
    mode: u=rw,g=,o=
  become: true
