---
# Configures OpenLDAP to require SSL connections. In today's "HTTPS Everywhere"
# world, this is just sensible.
#
# It will use the Let's Encrypt certificate that was generated for the server's
# primary domain. Accordingly, all LDAP connections will have to use a matching 
# URL, e.g. `ldaps://justdavis.com/`.

# Note: POSIX ACLs are tricky: this will only work if the ACL "mask" allows 
# these permissions. That mask basically boils down to "what are the basic 
# group permissions? (Just noting that here: resolving that is the 
# responsibility of whatever sets up the certificates in the first place.)
- name: Allow openldap Access to Existing Certificate Private Keys
  acl:
    path: /var/lib/acme/keys
    state: present
    etype: user
    entity: openldap
    permissions: "rX"
    recursive: true
    follow: true
  become: true
- name: Allow openldap Access to New Certificate Private Keys
  acl:
    path: /var/lib/acme/keys
    state: present
    etype: user
    entity: openldap
    permissions: "rX"
    default: true
    recursive: true
    follow: true
  become: true

- name: Ensure that slapd is Reloaded for New Certificates
  lineinfile:
    path: /etc/default/acme-reload
    line: 'SERVICES="$SERVICES slapd"'
  become: true

- template:
    src: templates/slapd-apparmor.j2
    dest: /etc/apparmor.d/local/usr.sbin.slapd
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
  register: slapd_apparmor
# This has to be applied right away, or the SSL config change will fail.
- service:
    name: apparmor
    state: reloaded
  become: true
  when: "{{ slapd_apparmor.changed }}"
# Not sure why, but applying these slapd config attributes via `ldap_attr` 
# fails. It seems they need to be written in a single transaction?
- template:
    src: templates/slapd-ssl.ldif.j2
    dest: /etc/ldap/slapd-ssl.ldif
  become: true
  register: slapd_ssl_ldif
- command: 'ldapmodify -Y EXTERNAL -H "ldapi:///" -f /etc/ldap/slapd-ssl.ldif'
  become: true
  when: "{{ slapd_ssl_ldif.changed }}"
  notify:
    - "Restart 'slapd'"
- template:
    src: templates/slapd-defaults.j2
    dest: /etc/default/slapd
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
  notify:
    - "Restart 'slapd'"

