---
# Specifies the entries that should be stored in the OpenLDAP directory.
#
# Yes, it seems a bit silly to duplicate all of the data in the directory here
# in YAML. But at our small scale, this actually makes things quite a bit 
# easier to manage.
#
# Note: These entries are primarily additive. Any modifications will likely 
# require additional tasks below to update/delete the existing data.

- name: Create LDAP OUs
  ldap_entry: 
    bind_dn: 'cn=admin,dc=justdavis,dc=com'
    bind_pw: "{{ vault_ldap_root_password }}"
    dn: "{{ item }}"
    objectClass: ['organizationalUnit']
  with_items:
    - 'ou=people,dc=justdavis,dc=com'
    - 'ou=groups,dc=justdavis,dc=com'
    - 'ou=services,dc=justdavis,dc=com'

# Create `ou=people` entries for each `people` entry (in `../vars/main.yml`).
# Note that the `ldap_entry` module being used here does not handles updates-- 
# only inserts.
- name: Create LDAP User Accounts
  ldap_entry:
    bind_dn: 'cn=admin,dc=justdavis,dc=com'
    bind_pw: "{{ vault_ldap_root_password }}"
    dn: "uid={{ item.key }},ou=people,dc=justdavis,dc=com"
    objectClass: ['inetOrgPerson', 'posixAccount']
    uid: "{{ item.key }}"
    cn: "{{ item.value.givenName }} {{ item.value.sn }}"
    displayName: "{{ item.value.givenName }} {{ item.value.sn }}"
    givenName: "{{ item.value.givenName }}"
    sn: "{{ item.value.sn }}"
    uidNumber: "{{ item.value.uidAndGidNumber }}"
    gidNumber: "{{ item.value.uidAndGidNumber }}"
    userPassword: "{SASL}{{ item.key }}@{{ domain | upper }}"
    loginShell: '/bin/bash'
    homeDirectory: "/home/{{ item.key }}"
    mail: "{{ item.value.mail }}"
  with_dict: "{{ people }}"
  no_log: true

# Create `ou=groups` entries for each `people` entry (in `../vars/main.yml`).
- name: Create LDAP User Groups
  ldap_entry:
    bind_dn: 'cn=admin,dc=justdavis,dc=com'
    bind_pw: "{{ vault_ldap_root_password }}"
    dn: "cn={{ item.key }},ou=groups,dc=justdavis,dc=com"
    objectClass: 'posixGroup'
    cn: "{{ item.key }}"
    gidNumber: "{{ item.value.uidAndGidNumber }}"
  with_dict: "{{ people }}"
  no_log: true

# Update email addresses, as needed.
- name: Update LDAP Email Addresses
  ldap_attr:
    bind_dn: 'cn=admin,dc=justdavis,dc=com'
    bind_pw: "{{ vault_ldap_root_password }}"
    dn: "uid={{ item.key }},ou=people,dc=justdavis,dc=com"
    state: exact
    name: mail
    values: "{{ item.value.mail }}"
  with_dict: "{{ people }}"
  no_log: true

