---

- name: Install
  apt: name={{ item }} update_cache=true cache_valid_time="{{ 60 * 15 }}"
  become: yes
  with_items:
    - apache2

- name: Firewall - Allow HTTPS
  ufw:
    rule: allow
    name: Apache Secure
  become: true

# Ensure that the certificate private keys allow for "named owner/group" ACL 
# entries to give specific non-root services access to them.
- name: Allow Group-Based Access to Certificate Private Keys
  copy:
    src: files/acme_perm
    dest: /var/lib/acme/conf/perm
    owner: acme
    group: acme
    mode: u=rw,g=r,o=r
  become: true
  register: copy_acme_perm
- name: Run acmetool to Apply Permissions Changes
  command: /usr/bin/acmetool --batch
  become: true
  become_user: acme
  when: copy_acme_perm.changed

- file:
    path: "{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: u=rwx,g=rwx,o=rx
  become: yes
  with_items:
    - "/var/apache2/{{ domain }}"
    - "/var/apache2/{{ domain }}/logs"
    - "/var/apache2/{{ domain }}/www"

- lineinfile:
    dest: /etc/apache2/ports.conf
    regexp: '^(#?)Listen 80'
    line: '#Listen 80'
  become: yes
  notify:
    - apache-restart

- apache2_module:
    state: present
    name: ssl
  become: yes
  notify:
    - apache-restart

- template:
    src: domain-ssl.conf
    dest: "/etc/apache2/sites-available/{{ domain }}-ssl.conf"
    mode: u=rw,g=rw,o=r
  become: yes
  notify:
    - apache-reload

- command: "/usr/sbin/a2ensite {{ domain }}-ssl.conf"
  args:
    creates: "/etc/apache2/sites-enabled/{{ domain }}-ssl.conf"
  become: yes
  notify:
    - apache-reload

