---

- name: Install
  apt: name={{ item }} update_cache=true cache_valid_time="{{ 60 * 15 }}"
  become: yes
  with_items:
    - apache2

- name: Firewall - Allow HTTPS
  ufw:
    rule: allow
    name: Apache Secure
  become: true

- file:
    path: "{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: u=rwx,g=rwx,o=rx
  become: yes
  with_items:
    - "/var/apache2/{{ domain }}"
    - "/var/apache2/{{ domain }}/logs"
    - "/var/apache2/{{ domain }}/www"

- name: Configure the Ports and IPs for Apache
  template:
    src: ports.conf.j2
    dest: /etc/apache2/ports.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: yes
  notify:
    - apache-restart

- apache2_module:
    state: present
    name: "{{ item }}"
  become: yes
  with_items:
    - ssl
    - rewrite
    # Used to proxy Jenkins and other apps:
    - [proxy, proxy_http, headers]
  notify:
    - apache-restart

- template:
    src: shared-ssl.conf
    dest: "/etc/apache2/conf-available/ssl.conf"
    mode: u=rw,g=rw,o=r
  become: yes
  notify:
    - apache-reload

- command: "/usr/sbin/a2enconf ssl.conf"
  args:
    creates: "/etc/apache2/conf-enabled/ssl.conf"
  become: yes
  notify:
    - apache-reload

- template:
    src: domain-ssl.conf
    dest: "/etc/apache2/sites-available/{{ domain }}-ssl.conf"
    mode: u=rw,g=rw,o=r
  become: yes
  notify:
    - apache-reload

- command: "/usr/sbin/a2ensite {{ domain }}-ssl.conf"
  args:
    creates: "/etc/apache2/sites-enabled/{{ domain }}-ssl.conf"
  become: yes
  notify:
    - apache-reload

