---

- name: Install Apache
  ansible.builtin.package:
    name: apache2
    state: present
  become: yes
  with_items:
    - apache2

- name: Firewall - Allow Apache HTTP
  ansible.builtin.ufw:
    rule: allow
    name: Apache
  become: true

- name: "Create Apache Directories"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: u=rwx,g=rwx,o=rx
  become: yes
  with_items:
    - "/var/apache2/{{ domain }}"
    - "/var/apache2/{{ domain }}/logs"
    - "/var/apache2/{{ domain }}/www"

- name: Configure the Ports and IPs for Apache
  ansible.builtin.template:
    src: ports.conf.j2
    dest: /etc/apache2/ports.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: yes
  notify:
    - apache-restart

- name: Enable Apache Modules
  community.general.apache2_module:
    state: present
    name: "{{ item }}"
  become: yes
  with_items:
    - ssl
    - rewrite
    # Used to proxy Jenkins and other apps:
    - [proxy, proxy_http, headers]
  notify:
    - apache-restart

- name: Create Apache HTTP Virtual Host Configuration
  ansible.builtin.template:
    src: domain.conf
    dest: "/etc/apache2/sites-available/{{ domain }}.conf"
    mode: u=rw,g=rw,o=r
  become: yes
  notify:
    - apache-reload

- name: Enable Apache HTTP Virtual Host Configuration
  ansible.builtin.command: "/usr/sbin/a2ensite {{ domain }}.conf"
  args:
    creates: "/etc/apache2/sites-enabled/{{ domain }}.conf"
  become: yes
  notify:
    - apache-reload

- name: Disable Default Apache HTTP Virtual Host Configuration
  ansible.builtin.command: "/usr/sbin/a2dissite 000-default.conf"
  args:
    removes: "/etc/apache2/sites-enabled/000-default.conf"
  become: yes
  notify:
    - apache-reload
