---

- name: Import tasks - certbot.yml
  ansible.builtin.import_tasks: certbot.yml

- name: Import tasks - apache.yml
  ansible.builtin.import_tasks: apache.yml

- name: Import tasks - test.yml
  ansible.builtin.import_tasks: test.yml
  tags: test
