---

# This MUST NOT be done in production, but is required for the tests to work.
- name: Trust Let's Encrypt Staging CA
  get_url:
    url: 'https://letsencrypt.org/certs/fakelerootx1.pem'
    dest: '/usr/local/share/ca-certificates/fakelerootx1.crt'
    owner: root
    group: staff
    mode: u=rw,g=r,o=r
  register: staging_ca_result
  become: true

- name: Update CA Certificates Index
  command: /usr/sbin/update-ca-certificates
  when: staging_ca_result.changed
  become: true

