---
# This playbook configures the Davis IT systems.
#
# Usage: This playbook can be run, as follows:
#
#     $ ansible-playbook site.yml

- name: Configure Eddings
  hosts: eddings.justdavis.com
  become: true
  gather_facts: true
  tasks:
    - name: Import role - eddings_base
      ansible.builtin.import_role:
        name: eddings_base
    # Configure networking, except during tests in AWS (because networking there is
    # completely different and incompatible).
    - name: Import role - eddings_networking
      ansible.builtin.import_role:
        name: eddings_networking
      when: not is_test
    - name: Import role - base
      ansible.builtin.import_role:
        name: base
    - name: Import role - zfs_pool
      ansible.builtin.import_role:
        name: zfs_pool
    - name: Import role - docker
      ansible.builtin.import_role:
        name: docker
    - name: Import role - virtual_machines
      ansible.builtin.import_role:
        name: virtual_machines
    - name: Import role - dns_server
      ansible.builtin.import_role:
        name: dns_server
    - name: Import role - apache
      ansible.builtin.import_role:
        name: apache
    - name: Import role - krb5_server
      ansible.builtin.import_role:
        name: krb5_server
    - name: Import role - ldap_server
      ansible.builtin.import_role:
        name: ldap_server
    - name: Import role - auth_client
      ansible.builtin.import_role:
        name: auth_client
    - name: Import role - file_server
      ansible.builtin.import_role:
        name: file_server
    - name: Import role - mail_server
      ansible.builtin.import_role:
        name: mail_server
    - name: Import role - postgresql_server
      ansible.builtin.import_role:
        name: postgresql_server
    - name: Import role - bookworm
      ansible.builtin.import_role:
        name: bookworm
    - name: Import role - arr_suite
      ansible.builtin.import_role:
        name: arr_suite
    - name: Import role - jellyfin
      ansible.builtin.import_role:
        name: jellyfin
    - name: Import role - immitch
      ansible.builtin.import_role:
        name: immitch
    # - import_role: name=nexus_server
    # - import_role: name=sonarqube_server
    # - import_role: name=jenkins_server
    # - import_role: name=spideroak

- name: Apply Common Configuration
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Import role - base
      ansible.builtin.import_role:
        name: base
    - name: Import role - auth_client
      ansible.builtin.import_role:
        name: auth_client
    - name: Import role - file_client
      ansible.builtin.import_role:
        name: file_client
    - name: Import role - user_karl
      ansible.builtin.import_role:
        name: user_karl
    - name: Import role - tarsnap
      ansible.builtin.import_role:
        name: tarsnap

- name: Configure Workstations
  hosts: workstations
  become: true
  gather_facts: true
  tasks:
    - name: Import role - workstation_apps
      ansible.builtin.import_role:
        name: workstation_apps
    - name: Import role - user_karl_devenv
      ansible.builtin.import_role:
        name: user_karl_devenv
