---
# This playbook configures the Davis IT systems.
#
# Usage: This playbook can be run, as follows:
#
#     $ ansible-playbook site.yml

- hosts: os_ubuntu_1604
  name: Bootstrap Ubuntu Hosts with Python 2.7
  gather_facts: false
  # Required with Ansible 2.3, in which most modules require Python 2.x.
  # Reference: https://groups.google.com/forum/#!topic/ansible-project/DUKzTho3OCI
  pre_tasks:
    - raw: sudo apt-get update -qq && sudo apt-get install -y -qq python2.7

- hosts: eddings.justdavis.com
  name: Configure Eddings
  gather_facts: true
  tasks:
    # Configure networking, except during tests in AWS (because networking there is
    # completely different and incompatible).
    - include: tasks/eddings_networking.yml
      when: is_test == false
    - include_role: name=base
    - include_role: name=virtual_machines
    - include_role: name=dns_server
    - include_role: name=apache
    - include_role: name=krb5_server
    - include_role: name=ldap_server
    - include_role: name=auth_client
    - include_role: name=vpn_server
    - include_role: name=file_server
    - include_role: name=mail_server
    - include_role: name=spideroak

- hosts: all
  name: Apply Common Configuration to Workstations
  gather_facts: true
  tasks:
    - include_role: name=base
    - include_role: name=auth_client
    - include_role: name=file_client
    - include_role: name=vpn_client
    - include_role: name=user_karl

