---
# This playbook configures the Davis IT systems.
#
# Usage: This playbook can be run, as follows:
#
#     $ ansible-playbook site.yml

- hosts: eddings.justdavis.com
  name: Configure Eddings
  become: true
  gather_facts: true
  tasks:
    # Configure networking, except during tests in AWS (because networking there is
    # completely different and incompatible).
    - import_role: name=eddings_networking
      when: is_test == false
    - import_role: name=base
    - import_role: name=virtual_machines
    - import_role: name=dns_server
    - import_role: name=apache
    - import_role: name=krb5_server
    - import_role: name=ldap_server
    - import_role: name=auth_client
    - import_role: name=vpn_server
    - import_role: name=file_server
    - import_role: name=mail_server
    - import_role: name=postgresql_server
    - import_role: name=jellyfin
    #- import_role: name=nexus_server
    #- import_role: name=sonarqube_server
    #- import_role: name=jenkins_server
    #- import_role: name=spideroak

- hosts: all
  name: Apply Common Configuration
  become: true
  gather_facts: true
  tasks:
    - import_role: name=base
    - import_role: name=auth_client
    - import_role: name=file_client
    - import_role: name=user_karl
    - import_role: name=tarsnap

- hosts: workstations
  name: Configure Workstations
  become: true
  gather_facts: true
  tasks:
    - import_role: name=workstation_apps
    - import_role: name=user_karl_devenv
    - import_role: name=vpn_client
      when: "'Microsoft' not in ansible_kernel"
