---

- name: Install SSSD and Related Packages
  apt: name={{ item }} update_cache=true cache_valid_time="{{ 60 * 15 }}"
  with_items:
    - sssd
    # Provides sssctl, for debugging/managing sssd.
    - sssd-tools
    # Allows use of sssctl.
    - sssd-dbus
    # If this is installed, users will also get a Kerberos ticket upon login.
    - krb5-user
  become: true

- name: Configure SSSD
  template:
    src: templates/sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    # SSSD will fail to start without exactly these permissions.
    mode: u=rw,g=,o=
  notify:
    - "Restart 'sssd'"
  become: true
