---

##
# Configures the system's networking correctly:
#
# * Use a public static IP on enp2s0f0.
# * Create a network bridge on enp2s0f0, for use by VMs.
##

- name: Install Network Bridging Utilities
  apt: name={{ item }} update_cache=true cache_valid_time="{{ 60 * 15 }}"
  with_items:
    - bridge-utils
  become: true

- name: Configure Network Interfaces
  copy:
    src: eddings_network_interfaces
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
  notify:
    - Restart Networking

