---

- name: Install OpenVPN
  ansible.builtin.apt:
    name: openvpn
  become: true

- name: Create OpenVPN Client Profile
  ansible.builtin.copy:
    content: "{{ hostvars['eddings.justdavis.com'].slurp_vpn_client_profiles.results | selectattr('item', 'equalto', inventory_hostname) | map(attribute='content') | list | first | b64decode }}"
    dest: "/etc/openvpn/client-justdavis.ovpn"
    owner: root
    group: root
    mode: u=rw,g=r,o=  # Contains keys, which should not be exposed.
  become: true
