---

- name: Restart arr_suite
  ansible.builtin.service:
    name: arr_suite
    state: restarted
  become: true

- name: Reload Systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
  become: true
