---

- name: Create OpenVPN iptables Script
  ansible.builtin.template:
    src: openvpn-iptables.sh.j2
    dest: /etc/init.d/openvpn-iptables
    owner: root
    group: root
    mode: u=rwx,g=rwx,o=r
  become: true
  notify:
    - Restart OpenVPN iptables Service

- name: Create OpenVPN iptables Service
  ansible.builtin.service:
    name: openvpn-iptables
    enabled: true
  become: true
  notify:
    - Restart OpenVPN iptables Service

- name: Firewall - Create OpenVPN Server Profile
  ansible.builtin.copy:
    src: openvpn-server.ufw.profile
    dest: /etc/ufw/applications.d/openvpn-server.ufw.profile
    mode: u=rw,g=r,o=r
  become: true
  register: ufw_profile_openvpn_server

- name: Firewall - Load OpenVPN Server Profile
  ansible.builtin.command:
    cmd: /usr/sbin/ufw app update openvpn-server.ufw.profile
  become: true
  when: ufw_profile_openvpn_server

- name: Firewall - Allow OpenVPN Server
  community.general.ufw:
    rule: allow
    name: OpenVPN Server
    to_ip: "{{ vpn_gateway_ip }}"
  become: true
