---

##
# Installs OpenVPN (client & server) from the project-maintained APT
# repository. This provides current releases, as opposed to the terrifyingly-
# out-of-date versions distrubted in the default Ubuntu/Debian repositories.
#
# References:
# * https://community.openvpn.net/openvpn/wiki/OpenvpnSoftwareRepos
##

- name: Install OpenVPN
  apt:
    name: openvpn
  become: true

