---

- name: Create User Home Directory
  ansible.builtin.command:
    cmd: /sbin/mkhomedir_helper karl
  args:
    creates: /home/karl
  become: true

- name: Create User .ssh Directory
  ansible.builtin.file:
    state: directory
    dest: /home/karl/.ssh
    mode: u=rwx,g=,o=
    owner: karl
    group: karl
  become: true

- name: Authorize karl for NOPASSWD sudo Use
  ansible.builtin.copy:
    dest: '/etc/sudoers.d/karl'
    content: |
      # Allow the `karl` account sudo access without requiring a password.
      karl ALL=(ALL) NOPASSWD:ALL
    owner: root
    group: root
    mode: u=w,g=r,o=
    validate: '/usr/sbin/visudo --check --file=%s'
  become: true

- name: Add karl to sudo Group
  # This seems redundant with the above sudoers.d entry, but is needed by polkit.
  ansible.builtin.user:
    name: karl
    groups: sudo
    append: true
  become: true

- name: Authorize SSH Keys
  ansible.posix.authorized_key:
    user: karl
    key: "{{ item }}"
  become: true
  loop: "{{ ssh_keys_karl_public }}"

# Did you know Homebrew is a perfectly cromulent option for dev tools on Linux?
# Me either, but it is!
- name: Install Homebrew
  ansible.builtin.shell:
    cmd: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    creates: /home/linuxbrew/.linuxbrew/bin/brew
  environment:
    NONINTERACTIVE: "1"
  become_user: karl
  become: true

- name: Configure Homebrew in Bash Profile
  ansible.builtin.copy:
    dest: /etc/profile.d/homebrew.sh
    content: |
      ##
      # This script configures Homebrew for all users on the system.
      #
      # Note: For login shells, Bash will source `/etc/profile`, which in turn sources all scripts in
      # `/etc/profile.d/`, including this one.
      ##

      # Homebrew shellenv setup for all users
      if [ -x /home/linuxbrew/.linuxbrew/bin/brew ]; then
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
      fi
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true

- name: Install chezmoi Using Homebrew
  community.general.homebrew:
    name: chezmoi
    state: present
    update_homebrew: true
  become_user: karl
  become: true

- name: Initialize chezmoi with dotfiles repo
  ansible.builtin.shell:
    cmd: set -o pipefail; echo "personal" | /home/linuxbrew/.linuxbrew/bin/chezmoi init --no-tty karlmdavis
    executable: /bin/bash
    creates: /home/karl/.local/share/chezmoi
  become_user: karl
  become: true

- name: Apply chezmoi dotfiles
  ansible.builtin.command:
    cmd: /home/linuxbrew/.linuxbrew/bin/chezmoi apply
    # Just checking for an arbitrary file that should exist if chezmoi has been applied.
    creates: /home/karl/.config/zellij/config.kdl
  become_user: karl
  become: true
