---

- name: Create User Home Directory
  ansible.builtin.command:
    cmd: /sbin/mkhomedir_helper karl
  args:
    creates: /home/karl
  become: true

- name: Create User .ssh Directory
  ansible.builtin.file:
    state: directory
    dest: /home/karl/.ssh
    mode: u=rwx,g=,o=
    owner: karl
    group: karl
  become: true

- name: Authorize karl for NOPASSWD sudo Use
  ansible.builtin.copy:
    dest: '/etc/sudoers.d/karl'
    content: |
      # Allow the `karl` account sudo access without requiring a password.
      karl ALL=(ALL) NOPASSWD:ALL
    owner: root
    group: root
    mode: u=w,g=r,o=
    validate: '/usr/sbin/visudo --check --file=%s'
  become: true

- name: Add karl to sudo Group
  # This seems redundant with the above sudoers.d entry, but is needed by polkit.
  ansible.builtin.user:
    name: karl
    groups: sudo
    append: true
  become: true

- name: Authorize SSH Keys
  ansible.posix.authorized_key:
    user: karl
    key: "{{ item }}"
  become: true
  loop: "{{ ssh_keys_karl_public }}"

- name: Copy SSH Public Key
  ansible.builtin.copy:
    content: "{{ ssh_key_karlmdavis.public }}"
    dest: "/home/karl/.ssh/id_rsa.pub"
    owner: karl
    group: karl
    mode: u=rw,g=r,o=r
  become: true

- name: Copy SSH Private Key
  ansible.builtin.copy:
    content: "{{ ssh_key_karlmdavis.private }}"
    dest: "/home/karl/.ssh/id_rsa"
    owner: karl
    group: karl
    mode: u=rw,g=,o=
  become: true
  no_log: true

- name: Install tmux
  ansible.builtin.package:
    name: tmux
    state: present
  become: true

- name: Create tmux Plugins Dir
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
  become: true
  become_user: karl
  with_items:
    - /home/karl/.tmux
    - /home/karl/.tmux/plugins

- name: Install tmux Plugin Manager
  ansible.builtin.git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: '/home/karl/.tmux/plugins/tpm'
    update: false
  become: true
  become_user: karl

- name: Install and Configure RCM
  ansible.builtin.import_role:
    name: karlmdavis.rcm-dotfiles
  vars:
    rcm_user: karl
    rcm_install_mode: default
    rcm_replace_existing_files: true
    rcm_repos:
      - repo: 'git@github.com:karlmdavis/dotfiles.git'
        dest: '/home/karl/.dotfiles-karlmdavis.git'
  become: false
