---

- name: Create User Home Directory
  command: /sbin/mkhomedir_helper karl
  args:
    creates: /home/karl
  become: true

- name: Create User .ssh Directory
  file: 
    state: directory
    dest: /home/karl/.ssh
    mode: u=rwx,g=,o= 
    owner: karl
    group: karl
  become: true

- name: Authorize karl for NOPASSWD sudo Use
  copy:
    dest: '/etc/sudoers.d/karl'
    content: |
      # Allow the `karl` account sudo access without requiring a password.
      karl ALL=(ALL) NOPASSWD:ALL
    user: root
    group: root
    mode: u=w,g=r,o=
    validate: '/usr/sbin/visudo --check --file=%s'
  become: true

- name: Add karl to sudo Group
  # This seems redundant with the above sudoers.d entry, but is needed by polkit.
  user:
    name: karl
    groups: sudo
    append: true
  become: true

- name: Authorize SSH Key
  authorized_key:
    user: karl
    key: "{{ ssh_key_karlmdavis.public }}"
  become: true

- name: Copy SSH Public Key
  copy: 
    content: "{{ ssh_key_karlmdavis.public }}" 
    dest: "/home/karl/.ssh/id_rsa.pub"
    owner: karl
    group: karl
    mode: u=rw,g=r,o=r
  become: true

- name: Copy SSH Private Key
  copy: 
    content: "{{ ssh_key_karlmdavis.private }}" 
    dest: "/home/karl/.ssh/id_rsa"
    owner: karl
    group: karl
    mode: u=rw,g=,o=
  become: true
  no_log: true

- name: Create Downloads Directory
  file:
    state: directory
    path: /home/karl/Downloads
  become: true
  become_user: karl

- name: Download tmux Release Bundle
  get_url:
    url: 'https://github.com/tmux/tmux/releases/download/2.6/tmux-2.6.tar.gz'
    dest: '/home/karl/Downloads/tmux-2.6.tar.gz'
  become: true
  become_user: karl

- name: Extract tmux Release Bundle
  unarchive:
    src: /home/karl/Downloads/tmux-2.6.tar.gz
    remote_src: true
    dest: /home/karl/Downloads
    creates: /home/karl/Downloads/tmux-2.6
  become: true
  become_user: karl

- name: Install tmux Prerequisites
  apt: name={{ item }} update_cache=true cache_valid_time="{{ 60 * 15 }}"
  with_items:
    - libevent-dev
    - libncurses-dev
  register: apt_sensors
  become: true

- name: Compile and Install tmux
  command: "{{ item }}"
  args:
    chdir: /home/karl/Downloads/tmux-2.6
    creates: /home/karl/bin/tmux
  become: true
  become_user: karl
  with_items:
    - /home/karl/Downloads/tmux-2.6/configure --prefix=/home/karl
    - make
    - make install

- name: Create tmux Plugins Dir
  file:
    state: directory
    path: "{{ item }}"
  become: true
  become_user: karl
  with_items:
    - /home/karl/.tmux
    - /home/karl/.tmux/plugins

- name: Install tmux Plugin Manager
  git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: '/home/karl/.tmux/plugins/tpm'
    update: false
  become: true
  become_user: karl

- name: Install and Configure RCM
  import_role:
    name: karlmdavis.rcm-dotfiles
  vars:
    rcm_user: karl
    rcm_install_mode: default
    rcm_replace_existing_files: true
    rcm_repos:
      - repo: 'git@github.com:karlmdavis/dotfiles.git'
        dest: '/home/karl/.dotfiles-karlmdavis.git'
