---

- name: Create User Home Directory
  ansible.builtin.command:
    cmd: /sbin/mkhomedir_helper karl
  args:
    creates: /home/karl
  become: true

- name: Create User .ssh Directory
  ansible.builtin.file:
    state: directory
    dest: /home/karl/.ssh
    mode: u=rwx,g=,o=
    owner: karl
    group: karl
  become: true

- name: Authorize karl for NOPASSWD sudo Use
  ansible.builtin.copy:
    dest: '/etc/sudoers.d/karl'
    content: |
      # Allow the `karl` account sudo access without requiring a password.
      karl ALL=(ALL) NOPASSWD:ALL
    owner: root
    group: root
    mode: u=w,g=r,o=
    validate: '/usr/sbin/visudo --check --file=%s'
  become: true

- name: Add karl to sudo Group
  # This seems redundant with the above sudoers.d entry, but is needed by polkit.
  ansible.builtin.user:
    name: karl
    groups: sudo
    append: true
  become: true

- name: Authorize SSH Keys
  ansible.posix.authorized_key:
    user: karl
    key: "{{ item }}"
  become: true
  loop: "{{ ssh_keys_karl_public }}"

- name: Get latest chezmoi release info
  ansible.builtin.uri:
    url: https://api.github.com/repos/twpayne/chezmoi/releases/latest
    return_content: yes
  register: chezmoi_release
  become: false

- name: Install chezmoi
  ansible.builtin.apt:
    deb: "https://github.com/twpayne/chezmoi/releases/download/{{ chezmoi_release.json.tag_name }}/chezmoi_{{ chezmoi_release.json.tag_name[1:] }}_linux_amd64.deb"
    state: present
  become: true

- name: Initialize chezmoi with dotfiles repo
  ansible.builtin.shell:
    cmd: echo "personal" | chezmoi init --no-tty karlmdavis
    creates: /home/karl/.local/share/chezmoi
  become_user: karl
  become: true

- name: Apply chezmoi dotfiles
  ansible.builtin.command:
    cmd: chezmoi apply
  become_user: karl
  become: true

- name: Create Git Config
  ansible.builtin.template:
    src: gitconfig.j2
    dest: /home/karl/.gitconfig
    owner: karl
    group: karl
    mode: u=rw,g=r,o=r
  become: true
