---

# Contains secrets only used by this role.
- name: Include variables - vars/vault.yml
  ansible.builtin.include_vars: vars/vault.yml

- name: Import tasks - install.yml
  ansible.builtin.import_tasks: install.yml
- name: Import tasks - config.yml
  ansible.builtin.import_tasks: config.yml
- name: Import tasks - jobs.yml
  ansible.builtin.import_tasks: jobs.yml
