---

- name: Restart bind9
  service:
    name: bind9
    state: restarted
  become: true
- name: Restart systemd-resolved
  service:
    name: systemd-resolved
    state: restarted
  become: true
- name: Restart systemd-networkd
  service:
    name: systemd-networkd
    state: restarted
  become: true
