---

##
# Configures the system's networking correctly:
#
# * Use a public static IP on enp2s0f0.
# * Create a network bridge on enp2s0f0, for use by VMs.
##

- name: Install Network Bridging Utilities
  ansible.builtin.package:
    name: bridge-utils
    state: present
  become: true

- name: Configure Network Interfaces
  ansible.builtin.copy:
    src: 00-installer-config.yaml
    dest: /etc/netplan/00-installer-config.yaml
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
  notify:
    - Run netplan apply
