---

- name: "Restart 'slapd'"
  ansible.builtin.service:
    name: slapd
    state: restarted
  become: true

- name: "Restart 'saslauthd'"
  ansible.builtin.service:
    name: saslauthd
    state: restarted
  become: true
