---

- name: Install Virtualization Packages
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
    cache_valid_time: "{{ 60 * 15 }}"
  with_items:
    - libvirt-daemon-system
    - virtinst
    - qemu-utils
    - python3-lxml
    - python3-libvirt
  become: true
