---

- name: "Restart 'clamav-daemon'"
  service:
    name: clamav-daemon
    state: restarted
  become: true

- name: "Restart 'amavis'"
  service:
    name: amavis
    state: restarted
  become: true

- name: "Run 'postmap' on 'virtual_mailbox_maps'"
  command: /usr/sbin/postmap /etc/postfix/virtual_mailbox_maps
  become: true

- name: "Restart 'postfix'"
  service:
    name: postfix
    state: restarted
  become: true

- name: 'Compile Dovecot Global Sieve Rules'
  command: /usr/bin/sievec /var/lib/dovecot/sieve.d/
  become: true

- name: "Restart 'dovecot'"
  service:
    name: dovecot
    state: restarted
  become: true

