---

- name: "Restart 'clamav-daemon'"
  ansible.builtin.service:
    name: clamav-daemon
    state: restarted
  become: true

- name: "Restart 'amavis'"
  ansible.builtin.service:
    name: amavis
    state: restarted
  become: true

- name: Update opendkim DNS Include
  ansible.builtin.command:
    cmd: /bin/cp /etc/dkimkeys/a.txt /etc/bind/dkim-{{ domain }}.record
  become: true

- name: "Restart 'opendkim'"
  ansible.builtin.service:
    name: opendkim
    state: restarted
  become: true

- name: "Run 'postmap' on 'virtual_alias_maps'"
  ansible.builtin.command:
    cmd: /usr/sbin/postmap /etc/postfix/virtual_alias_maps
  become: true

- name: "Restart 'postfix'"
  ansible.builtin.service:
    name: postfix
    state: restarted
  become: true

- name: 'Compile Dovecot Global Sieve Rules'
  ansible.builtin.command:
    cmd: /usr/bin/sievec /var/lib/dovecot/sieve.d/
  become: true

- name: "Restart 'dovecot'"
  ansible.builtin.service:
    name: dovecot
    state: restarted
  become: true
