---

- name: Create Group Share Directory Root
  file:
    state: directory
    path: /var/lib/samba/groupshares
    owner: root
    group: sambashare
    mode: u=rwx,g=rwx,o=t
  become: true

- name: Create Group Share Directories
  file:
    state: directory
    path: "/var/lib/samba/groupshares/{{ item.key }}"
    owner: "{{ item.value.owner }}"
    group: "{{ item.value.group }}"
    mode: "{{ item.value.mode }}"
  with_dict:
    karlanderica:
      owner: karl
      group: karlanderica
      mode: u=rwxs,g=rwxs,o=t
    sysadmin:
      owner: karl
      group: administrators_posix
      mode: u=rwxs,g=rwxs,o=rxst
  become: true

- name: Create User Share Directories
  file:
    state: directory
    path: "/var/lib/samba/usershares/{{ item.key }}"
    owner: "{{ item.key }}"
    group: "{{ item.key }}"
    mode: u=rwxs,g=rwxs,o=
  with_dict: "{{ people }}"
  become: true

- name: Create Service Principal for Samba Server
  krb_principal:
    name: "cifs/eddings.{{ domain }}"
    policy: services
  become: true

- name: Create Service Keytab for Samba Server
  script: "roles/ldap_server/files/add-keytab.sh --principal cifs/eddings.{{ domain }} --keytab /etc/samba/smbd.keytab"
  become: true

- file:
    path: /etc/samba/smbd.keytab
    state: file
    owner: root
    group: root
    mode: 'u=r,g=r,o='
  become: true
  notify:
    - "Restart 'samba'"

- name: Configure smb.conf
  template:
    src: templates/smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
  notify:
    - "Restart 'samba'"

