---

- meta: flush_handlers

- name: Create Test User Home Share Directory
  file:
    state: directory
    path: /var/lib/samba/users/test
    owner: test
    group: test
    mode: u=rwx,g=rx,o=
  become: true

- name: Wait for Samba Server
  wait_for:
    port: 139
    delay: 5

- name: List Samba Shares
  command: "/usr/bin/smbclient --list=eddings.{{ domain }} --no-pass"
  register: smbclient_list_result
  failed_when: smbclient_list_result.rc != 0 or 'karlanderica' not in smbclient_list_result.stdout
  changed_when: false

- name: Acquire Kerberos Auth (as test)
  expect:
    command: "/usr/bin/kinit {{ test_username }}"
    responses:
      "^Password for .*: ": "{{ test_password }}"
  changed_when: false

- name: Browse Samba User Share
  command: "/usr/bin/smbclient //eddings.{{ domain }}/{{ test_username }} --kerberos --command ls"
  register: smbclient_ls_result
  failed_when: smbclient_ls_result.rc != 0 or 'blocks available' not in smbclient_ls_result.stdout
  changed_when: false

