---

- set_fact: spideroakone_device="{{ (ansible_hostname + '-test2') if is_test else ansible_hostname }}"
- name: Create Temporary Setup File
  template:
    src: setup.json.j2
    dest: /home/backups/spideroak-setup.json
    owner: backups
    group: backups
    mode: u=rw,g=,o=
  become: true

- name: Run SpiderOak Setup
  # This task typically takes hours to complete. Backgrounded to ensure that timeouts and SSH connection failures don't cause the task to fail.
  shell: "/usr/bin/nohup /usr/bin/SpiderOakONE --setup=/home/backups/spideroak-setup.json &> /home/backups/spideroak-setup.log &"
  args:
    executable: /bin/bash
    creates: /home/backups/spideroak-setup.log
  become_user: backups
  become: true

- name: Remove Temporary Setup File
  file:
    path: /home/backups/spideroak-setup.json
    state: absent
  become: true

