---

- include: install.yml

- name: Check for SpiderOak Config
  stat:
    path: /home/backups/.config/SpiderOakONE/pandora_sqliite_database
  failed_when: false
  register: stat_spideroak_db
  become: true

# Initial setup takes over an hour; no time for that in tests.
- include: account.yml
  when: is_test == false and stat_spideroak_db.stat.isreg is not defined

- include: service.yml

