---
dependencies:

  # Apply and configure the `karlmdavis.tested-bind` role.
  - role: karlmdavis.tested-bind
    eddings_public_ip: "{{ hostvars['eddings.justdavis.com']['public_ip'] }}"
    reverse_zone_name: "{{ eddings_public_ip.split('.')[2] + '.' + eddings_public_ip.split('.')[1] + '.' + eddings_public_ip.split('.')[0] + '.in-addr.arpa' }}"
    zones:
      - {name: "{{ domain }}", template_source: 'roles/dns_server/templates/db.justdavis.com.j2'}
      - {name: "{{ domain_alias }}", template_source: 'roles/dns_server/templates/db.davisonlinehome.name.j2'}
      - {name: "{{ reverse_zone_name }}", template_source: 'roles/dns_server/templates/db.reverse_zone.j2'}
    forwarders:
      # Google's Public DNS Servers: https://developers.google.com/speed/public-dns/
      - 8.8.8.8
      - 8.8.4.4
    zone_transfer_peers:
      # Gandi's ns6.gandi.net secondary name server
      - 217.70.177.40

