---
dependencies:

  # Before the L-P.acmetool role can be enabled, we need to open the firewall.
  - role: apache_pre

  # Apply and configure the `L-P.acmetool` role. This will start a Let's Encrypt client that listens on port 
  # 80, answering LE challenges, and redirecting all other traffic to port 443.
  # LE certificates will be created as `/var/lib/acme/live/HOSTNAME/{cert,chain,fullchain,privkey}`.
  - role: L-P.acmetool
    become: true
    acmetool_email: "{{ domain_webmaster }}"
    acmetool_domains: "{{ [domain] | union(domain_site_aliases) | join(' ') }}"
    acmetool_server: "{{ 'https://acme-v01.api.letsencrypt.org/directory' if not is_test else 'https://acme-staging.api.letsencrypt.org/directory' }}"

