---

- name: Import tasks - config.yml
  ansible.builtin.import_tasks: config.yml
- name: Import tasks - sensors.yml
  ansible.builtin.import_tasks: sensors.yml
  when: "'Microsoft' not in ansible_kernel"

- name: Import tasks - test.yml
  ansible.builtin.import_tasks: test.yml
  tags: test
