---

- name: Install Sensors Utilities
  apt: name={{ item }} update_cache=true cache_valid_time="{{ 60 * 15 }}"
  with_items:
    - lm-sensors
  register: apt_sensors
  become: true

- name: Detect Sensors
  command: /usr/sbin/sensors-detect --auto
  become: true
  when: apt_sensors.changed

# TODO: Are sensor modules needed?
# TODO: Do we need to run `sudo service kmod start`?

# At this point, temperature sensors are available and can be checked by running:
#     $ sensors

