---

- meta: flush_handlers

- name: Get Kerberos Ticket for Test User
  expect:
    command: "/usr/bin/kinit {{ test_username }}"
    responses:
      "^Password for .*: ": "{{ test_password }}"
  when: ansible_distribution != 'Ubuntu' or ansible_distribution_release != 'trusty'
  changed_when: false
  no_log: true
- name: Get Kerberos Ticket for Test User
  shell: |
    set timeout 30
    
    # Run the kinit command and send it the password.
    spawn /usr/bin/kinit {{ test_username }}
    expect -re "Password for .*: "
    send "{{ test_password }}\n"
    
    # Wait for the kinit command to exit.
    expect eof
    
    # Catch the kinit command's exit status and save it to the `result` variable.
    catch wait result
    
    # Exit this script with the kinit command's return code.
    exit [lindex $result 3]
  args:
    executable: /usr/bin/expect
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'
  changed_when: false
  no_log: true

- name: Browse Samba User Share
  command: "/usr/bin/smbclient //eddings.karlanderica.{{ domain }}/{{ domain }} --kerberos --directory users/{{ test_username }} --command ls"
  register: smbclient_ls_result
  failed_when: smbclient_ls_result.rc != 0 or 'blocks available' not in smbclient_ls_result.stdout
  changed_when: false
