---

- meta: flush_handlers

# This MUST NOT be done in production, but is required for the tests to work.
- name: Trust Let's Encrypt Staging CA
  get_url:
    url: 'https://letsencrypt.org/certs/fakelerootx1.pem'
    dest: '/usr/local/share/ca-certificates/fakelerootx1.crt'
    owner: root
    group: staff
    mode: u=rw,g=r,o=r
  register: download_staging_ca_result
  become: true
  when: is_test == true

- name: Update CA Certificates Index
  command: /usr/sbin/update-ca-certificates
  when: download_staging_ca_result.changed
  become: true

- name: Test Kerberos Auth
  expect:
    command: "/usr/bin/kinit {{ test_username }}"
    responses:
      "^Password for .*: ": "{{ test_password }}"
  register: kinit_result
  failed_when: kinit_result.rc != 0

# This verifies that GSSAPI/Kerberos integration is working for the LDAP client utilities. Note
# that the above kinit test command obtained the Kerberos ticket needed.
- name: 'Test LDAP Search (GSSAPI)'
  command: "/usr/bin/ldapsearch -Y GSSAPI -H ldaps://{{ domain }} -b dc=justdavis,dc=com"
  register: ldap_search_gssapi_result
  failed_when: ldap_search_gssapi_result.rc != 0 or test_user_dn not in ldap_search_gssapi_result.stdout

