---

##
# Installs and configures a mail server. Postfix will be used for the MTA.
#
# Will enable and configure Postfix spam and virus filtering. Amavis will be 
# used to coordinate all of that and will be configured to use several tools, 
# such as SpamAssassin and ClamAV, to do the heavy lifting.
##

- debconf:
    name: "{{ item.question.split('/')[0] }}"
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  no_log: "{{ item.vtype == 'password' }}"
  changed_when: false
  become: true
  with_items:
    - { question: 'postfix/main_mailer_type', vtype: 'select', value: 'Internet Site' }
    - { question: 'postfix/mailname', vtype: 'string', value: "{{ domain }}" }
    - { question: 'postfix/root_address', vtype: 'string', value: "karl@{{ domain }}" }
    - { question: 'postfix/destinations', vtype: 'string', value: "$myhostname, {{ domain }}, eddings.{{ domain }}, localhost.{{ domain }}, localhost" }
    - { question: 'postfix/mynetworks', vtype: 'string', value: '127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128' }
    - { question: 'postfix/mailbox_limit', vtype: 'string', value: 'string' }
    - { question: 'postfix/protocols', vtype: 'select', value: 'all' }

- name: Install
  apt: name={{ item }} update_cache=true cache_valid_time="{{ 60 * 15 }}"
  with_items:
    - postfix
    - dovecot-imapd
    - dovecot-ldap
    - dovecot-lmtpd
    - dovecot-sieve
    # Spam and Virus Filtering Tools:
    - amavisd-new
    - spamassassin
    - clamav-daemon
    - libnet-dns-perl
    - libmail-spf-perl
    - pyzor
    - razor
  become: true

- name: Create 'vmail' User and Group
  user:
    name: vmail
    createhome: false
    shell: /bin/false
    system: true
  become: true

- name: Add 'postfix' User to 'vmail' Group
  user:
    name: postfix
    groups: vmail
    append: true
  become: true

- name: Lookup 'vmail' UID
  command: id --user vmail
  register: uid_vmail
  changed_when: false

- name: Lookup 'vmail' GID
  command: id --group vmail
  register: gid_vmail
  changed_when: false

- name: Create Mail Directory
  file:
    path: /var/vmail
    state: directory
    owner: vmail
    group: vmail
    mode: u=rwx,g=rwx,o=
  become: true

- name: Add 'clamav' User to 'amavis' Group
  user:
    name: clamav
    groups: amavis
    append: true
  become: true
  notify:
    - "Restart 'clamav-daemon'"

- name: Add 'amavis' User to 'clamav' Group
  user:
    name: amavis
    groups: clamav
    append: true
  become: true

- name: Create Razor Config
  command: /usr/bin/razor-admin -create
  args:
    creates: /var/lib/amavis/.razor/servers.discovery.lst
  become: true
  become_user: amavis

- name: Register Razor Account
  command: /usr/bin/razor-admin -register
  args:
    creates: /var/lib/amavis/.razor/identity
  become: true
  become_user: amavis

- name: Discover Pyzor Servers
  command: /usr/bin/pyzor discover
  args:
    creates: /var/lib/amavis/.pyzor/servers
  become: true
  become_user: amavis

- name: Configure Postfix main.cf
  lineinfile:
    dest: /etc/postfix/main.cf
    regexp: "^{{ item.key }} *=.*"
    line: "{{ item.key }} = {{ item.value }}"
  with_dict:
    # We DON'T want to handle the primary domain via the local transport; we'll
    # handle it the same way as all of the other virtual domains.
    'mydestination': ''
    'mydomain': "{{ domain }}"
    'myhostname': "eddings.{{ domain }}"
    # We want to use Maildir, rather than mbox, as it's easier to admin.
    'home_mailbox': 'Maildir/'
    # Set Postfix to use SASL for auth.
    'smtpd_sasl_local_domain': ''
    'smtpd_sasl_auth_enable': 'yes'
    'broken_sasl_auth_clients': 'yes'
    'smtpd_sasl_security_options': 'noanonymous,noplaintext'
    'smtpd_sasl_tls_security_options': 'noanonymous'
    # Require TLS for all SASL authentication attempts.
    'smtpd_tls_auth_only': 'yes'
    # Enable opportunistic encryption for connections to other SMTP servers.
    'smtp_tls_security_level': 'may'
    'smtpd_tls_security_level': 'may'
    'smtpd_tls_key_file': "/var/lib/acme/live/{{ domain }}/privkey"
    'smtpd_tls_cert_file': "/var/lib/acme/live/{{ domain }}/cert"
    # The CAfile must contain the chain for both the cert_file and the certs offerred by all remote clients.
    'smtpd_tls_CAfile': '/etc/ssl/certs/ca-certificates.crt'
    # Only allow authenticated clients to send mail.
    #'smtpd_recipient_restrictions': 'permit_sasl_authenticated,permit_mynetworks,reject_unauth_destination'
    'smtpd_relay_restrictions': 'permit_mynetworks,permit_sasl_authenticated,reject_unauth_destination'
    # Ensure that Postfix uses its own keytab.
    'import_environment': 'KRB5_KTNAME=/etc/postfix/krb5.keytab'
    # Configure the virtual domains to handle.
    'virtual_mailbox_base': '/var/vmail'
    'virtual_uid_maps': "static:{{ uid_vmail.stdout }}"
    'virtual_gid_maps': "static:{{ gid_vmail.stdout }}"
    'virtual_mailbox_domains': "{{ domain }} {{ domain_alias }}"
    'virtual_alias_maps': 'hash:/etc/postfix/virtual_alias_maps'
    # Send mail to Amavis for spam and virus filtering.
    'content_filter': 'smtp-amavis:[127.0.0.1]:10024'
    # Use Dovecot's LMTP service for delivery of virtual mail. This allows the
    # use of Dovecot's sieve to ensure that incoming mail flagged as spam is
    # dropped into Junk folders, rather than user's INBOXes.
    'virtual_transport': 'lmtp:unix:private/dovecot-lmtp'
  become: true
  notify:
    - "Restart 'postfix'"

- name: Configure Postfix Virtual Aliases
  copy:
    dest: /etc/postfix/virtual_alias_maps
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    # Each entry here defines an email address that will be accepted, and then 
    # the `virtual_mailbox_base` subdirectory that mail for that address will 
    # be delivered to. Each subdirectory's trailing `/` indicates that the 
    # Maildir format should be used and MUST be present, else mail will be 
    # delivered to an mbox file (which we don't want).
    # I've organized it as follows: 1) canonical addresses, 2) system user 
    # aliases, 3) other aliases.
    # Each of the targets must correspond to a single account in LDAP, as 
    # our Dovecot config only supports a 1:1 relationship between logins and
    # Maildirs.
    content: |
      postmaster@{{ domain }}                    karl@{{ domain }}
      acme@eddings.{{ domain }}                  karl@{{ domain }}
      root@eddings.{{ domain }}                  karl@{{ domain }}
      {{ test_username }}@{{ domain }}           {{ test_username }}@{{ domain }}
      {{ test_username }}_alias@{{ domain }}     {{ test_username }}@{{ domain }}
  become: true
  notify:
    - "Run 'postmap' on 'virtual_alias_maps'"

- name: Configure SASL for Postfix
  copy:
    dest: /etc/postfix/sasl/smtpd.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    content: |
      pwcheck_method: saslauthd
  become: true
  notify:
    - "Restart 'postfix'"

- name: Configure Amavis
  lineinfile:
    name: /etc/amavis/conf.d/50-user
    insertbefore: '^1;.*'
    # Note: Have to hackily handle the regex control chars in the keys here.
    regexp: "^[\\$@]{{ item.key[1:] }} = .*"
    line: "{{ item.key }} = {{ item.value }};"
  with_dict:
    # Ensure that all valid email domains are filtered.
    '@local_domains_acl': "( \".{{ domain }}\", \".{{ domain_alias }}\" )"
    # Always tag mail with spam score headers.
    '$sa_tag_level_deflt': '-9999'
    # Anything above this score will get an `X-Spam-Flag: YES` header, which 
    # will cause Dovecot's sieve rules to file it as junk/spam.
    '$sa_tag2_level_deflt': '5'
    '$sa_spam_subject_tag': "''"
    # Until spam scoring is dialed in, deliver all mail.
    # Note: The Debian default for `$sa_tag2_level_deflt` and `$sa_kill_level_deflt` is 6.31.
    # Note: It only makes sense to maintain the relationship: sa_tag_level <= sa_tag2_level <= sa_kill_level < sa_dsn_cutoff <= sa_quarantine_cutoff_level 
    '$sa_kill_level_deflt': '9999'
    '$sa_dsn_cutoff_level': '9999'
    '$sa_quarantine_cutoff_level': '9999'
    '$final_banned_destiny': 'D_PASS'
    '$final_spam_destiny': 'D_PASS'
  become: true
  notify:
    - "Restart 'amavis'"

- name: Configure ClamAV Permissions for Amavis
  lineinfile:
    name: /etc/clamav/clamd.conf
    regexp: '^AllowSupplementaryGroups.*'
    line: "AllowSupplementaryGroups true"
  become: true
  notify:
    - "Restart 'clamav-daemon'"

- name: Enable Spam and Virus Filtering in Amavis
  blockinfile:
    name: /etc/amavis/conf.d/15-content_filter_mode
    insertbefore: '^1;.*'
    marker: "# {mark} ANSIBLE-MANAGED BLOCK: {{ item.key }}"
    block: "{{ item.value }}"
  with_dict:
    'virus': |
      @bypass_virus_checks_maps = (
         \%bypass_virus_checks, \@bypass_virus_checks_acl, \$bypass_virus_checks_re);
    'spam': |
      @bypass_spam_checks_maps = (
         \%bypass_spam_checks, \@bypass_spam_checks_acl, \$bypass_spam_checks_re);
  become: true
  notify:
    - "Restart 'amavis'"

- name: Configure Cron to Remove Old Quarantined Viruses
  cron:
    name: Remove Old Quarantined Viruses
    special_time: daily
    job: /usr/bin/find /var/lib/amavis/virusmails/ -name "virus-*" -mtime +365 -exec rm {} ; &>> /var/log/quarantine_cleanup.log
  become: true

# At some point, we'll need to examine how to train/retrain the SpamAssassin 
# filter being used by Amavis. When that need arises, this is so far the best
# reference I've found: 
# <https://finninday.net/wiki/index.php/Amavis_and_Spamassassin_howto>.

- name: Configure Postfix Services for Amavis
  template:
    src: postfix/master.cf.j2
    dest: /etc/postfix/master.cf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
  notify:
    - "Restart 'postfix'"

# The Dovecot config here isn't too exciting, it's basically just setting it up
# to auth via LDAP. Dovecot's sieve plugin is used, along with the amavis spam
# filtering settings above, to ensure that each user can actually manage their
# spam: the spam is delivered into their Maildir, in a separate IMAP folder.
# The following sieve config references were helpful:
# * https://wiki1.dovecot.org/LDA/Sieve#SpamAssassin.2BAC8-Amavis_tagged_mail_filtering
# * https://gist.github.com/MartinEnders/c3bbbc6ce5145658451d
# * https://wiki2.dovecot.org/HowTo/PostfixDovecotLMTP#preview
- name: Configure Dovecot
  template:
    src: "dovecot/{{ item.name }}.j2"
    dest: "/etc/dovecot/{{ item.path }}{{ item.name }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
  with_items:
    - { name: '10-master.conf', path: 'conf.d/' }
    - { name: '10-mail.conf', path: 'conf.d/' }
    - { name: '10-auth.conf', path: 'conf.d/' }
    - { name: 'auth-ldap.conf.ext', path: 'conf.d/' }
    - { name: 'dovecot-ldap.conf.ext', path: '' }
    - { name: '10-logging.conf', path: 'conf.d/' }
    - { name: '10-ssl.conf', path: 'conf.d/' }
    - { name: '15-mailboxes.conf', path: 'conf.d/' }
    - { name: '20-lmtp.conf', path: 'conf.d/' }
    - { name: '90-sieve.conf', path: 'conf.d/' }
  notify:
    - "Restart 'dovecot'"

- name: Create Dovecot Global Sieve Rules Directory
  file:
    path: /var/lib/dovecot/sieve.d
    state: directory
    owner: root
    group: vmail
    mode: u=rwx,g=rx,o=rx
  become: true

- name: Configure Dovecot Global Sieve Rules
  template:
    src: "dovecot/{{ item }}.j2"
    dest: "/var/lib/dovecot/sieve.d/{{ item }}"
    owner: root
    group: vmail
    mode: u=rw,g=r,o=r
  become: true
  with_items:
    - '10-spam.sieve'
  notify:
    - 'Compile Dovecot Global Sieve Rules'

