---

- name: Create 'vmail' User and Group
  user:
    name: vmail
    createhome: false
    shell: /bin/false
    system: true
  become: true

- name: Add 'postfix' User to 'vmail' Group
  user:
    name: postfix
    groups: vmail
    append: true
  become: true

- name: Lookup 'vmail' UID
  command: id --user vmail
  register: uid_vmail
  changed_when: false

- name: Lookup 'vmail' GID
  command: id --group vmail
  register: gid_vmail
  changed_when: false

- name: Create Mail Directory
  file:
    path: /var/vmail
    state: directory
    owner: vmail
    group: vmail
    mode: u=rwx,g=rwx,o=
  become: true

- name: Configure Postfix main.cf
  lineinfile:
    dest: /etc/postfix/main.cf
    regexp: "^{{ item.key }} *=.*"
    line: "{{ item.key }} = {{ item.value }}"
  with_dict:
    # We DON'T want to handle the primary domain via the local transport; we'll
    # handle it the same way as all of the other virtual domains.
    'mydestination': ''
    'mydomain': "{{ domain }}"
    'myhostname': "eddings.{{ domain }}"
    # We want to use Maildir, rather than mbox, as it's easier to admin.
    'home_mailbox': 'Maildir/'
    # Set Postfix to use SASL for auth.
    'smtpd_sasl_local_domain': ''
    'smtpd_sasl_auth_enable': 'yes'
    'broken_sasl_auth_clients': 'yes'
    'smtpd_sasl_security_options': 'noanonymous,noplaintext'
    'smtpd_sasl_tls_security_options': 'noanonymous'
    # Require TLS for all SASL authentication attempts.
    'smtpd_tls_auth_only': 'yes'
    # Enable opportunistic encryption for connections to other SMTP servers.
    'smtp_tls_security_level': 'may'
    'smtpd_tls_security_level': 'may'
    'smtpd_tls_key_file': "/var/lib/acme/live/{{ domain }}/privkey"
    'smtpd_tls_cert_file': "/var/lib/acme/live/{{ domain }}/cert"
    # The CAfile must contain the chain for both the cert_file and the certs offerred by all remote clients.
    'smtpd_tls_CAfile': '/etc/ssl/certs/ca-certificates.crt'
    # Only allow authenticated clients to send mail.
    #'smtpd_recipient_restrictions': 'permit_sasl_authenticated,permit_mynetworks,reject_unauth_destination'
    'smtpd_relay_restrictions': 'permit_mynetworks,permit_sasl_authenticated,reject_unauth_destination'
    # Ensure that Postfix uses its own keytab.
    'import_environment': 'KRB5_KTNAME=/etc/postfix/krb5.keytab'
    # Configure the virtual domains to handle.
    'virtual_mailbox_base': '/var/vmail'
    'virtual_uid_maps': "static:{{ uid_vmail.stdout }}"
    'virtual_gid_maps': "static:{{ gid_vmail.stdout }}"
    'virtual_mailbox_domains': "{{ domain }} {{ domain_alias }}"
    'virtual_mailbox_maps': 'hash:/etc/postfix/virtual_mailbox_maps'
  become: true
  notify:
    - "Restart 'postfix'"

- name: Configure Postfix Virtual Users and Aliases
  copy:
    dest: /etc/postfix/virtual_mailbox_maps
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    # Each entry here defines an email address that will be accepted, and then 
    # the `virtual_mailbox_base` subdirectory that mail for that address will 
    # be delivered to. Each subdirectory's trailing `/` indicates that the 
    # Maildir format should be used and MUST be present, else mail will be 
    # delivered to an mbox file (which we don't want).
    # I've organized it as follows: 1) canonical addresses, 2) system user 
    # aliases, 3) other aliases.
    content: |
      karl@{{ domain }}              karl@{{ domain }}/
      acme@eddings.{{ domain }}      karl@{{ domain }}/
      root@eddings.{{ domain }}      karl@{{ domain }}/
      foo@example.com                bar/
  become: true
  notify:
    - "Run 'postmap' on 'virtual_mailbox_maps'"

- name: Configure SASL for Postfix
  copy:
    dest: /etc/postfix/sasl/smtpd.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    content: |
      pwcheck_method: saslauthd
  become: true
  notify:
    - "Restart 'postfix'"

