---

- debconf:
    name: "{{ item.question.split('/')[0] }}"
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  no_log: "{{ item.vtype == 'password' }}"
  changed_when: false
  become: true
  with_items:
    - { question: 'postfix/main_mailer_type', vtype: 'select', value: 'Internet Site' }
    - { question: 'postfix/mailname', vtype: 'string', value: "{{ domain }}" }
    - { question: 'postfix/root_address', vtype: 'string', value: "karl@{{ domain }}" }
    - { question: 'postfix/destinations', vtype: 'string', value: "$myhostname, {{ domain }}, eddings.{{ domain }}, localhost.{{ domain }}, localhost" }
    - { question: 'postfix/mynetworks', vtype: 'string', value: '127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128' }
    - { question: 'postfix/mailbox_limit', vtype: 'string', value: 'string' }
    - { question: 'postfix/protocols', vtype: 'select', value: 'all' }

- name: Install
  apt: name={{ item }} update_cache=true cache_valid_time="{{ 60 * 15 }}"
  with_items:
    - postfix
  become: true

