---

##
# Postfix on Debian is not properly configured to run `opendkim`: the `smtpd`
# service is (by default) run inside a chroot environment at
# `/var/spool/postfix/`, which doesn't have access to the OpenDKIM socket file.
#
# This config adds that file (and friends) back into the chroot environment
# using a mount bind. This fix is adapted from
# <https://unix.stackexchange.com/a/74491> and
# <https://github.com/webmin/webmin/issues/58>.
##

- name: Add 'postfix' User to 'opendkim' Group
  ansible.builtin.user:
    name: postfix
    groups: opendkim
    append: true
  become: true

- name: Create `/var/run` Directory in Postfix chroot
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  with_items:
    - /var/spool/postfix/var
    - /var/spool/postfix/var/run
  become: true

- name: Create Mount Point for OpenDKIM in Postfix chroot
  ansible.builtin.file:
    state: directory
    path: /var/spool/postfix/var/run/opendkim
    owner: opendkim
    group: opendkim
    mode: u=rwx,g=rx,o=rx
  become: true

- name: Verify dpkg Override for OpenDKIM Mount Point
  ansible.builtin.command:
    cmd: dpkg-statoverride --list /var/spool/postfix/var
  register: dpkg_override_postfix_var
  changed_when: false
  failed_when: false

- name: Configure dpkg to Handle OpenDKIM Mount Point Correctly
  ansible.builtin.command:
    cmd: dpkg-statoverride --add root root 755 /var/spool/postfix/var
  become: true
  when: dpkg_override_postfix_var.rc != 0

- name: Mount OpenDKIM in Postfix chroot
  ansible.posix.mount:
    name: /var/spool/postfix/var/run/opendkim
    src: /var/run/opendkim
    fstype: bind
    opts: defaults,nodev,bind
    state: mounted
  become: true
