---

- meta: flush_handlers

- name: Install Test Utilities
  apt: name={{ item }} update_cache=true cache_valid_time="{{ 60 * 15 }}"
  with_items:
    - swaks
  become: true

- name: Send Mail (Unauthenticated and In-Network)
  command: "/usr/bin/swaks --server localhost:25 --to karl@{{ domain }} --header 'Subject: Test Mail - Unauthenticated and In-Network'"
  changed_when: false

- name: Send Mail (Authenticated and Out-of-Network)
  local_action: "command /usr/bin/swaks --server {{ hostvars['eddings.justdavis.com']['ansible_host'] }}:25 --tls --auth-user test --auth-password {{ lookup('password', '/tmp/justdavis-ansible-test-password chars=ascii_letters,digits,punctuation length=32') }} --to karl@{{ domain }} --header 'Subject: Test Mail - Authenticated and Out-of-Network'"
  changed_when: false

# Try to send a message with the EICAR virus filter test pattern, verify it's quarantined.
# Reference: http://www.eicar.org/86-0-Intended-use.html
- name: Write Virus Test Pattern
  copy:
    dest: /tmp/eicar
    content: 'X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*'

- name: Send Mail (Unauthenticated, In-Network, and with Virus Pattern)
  command: "/usr/bin/swaks --server localhost:25 --to karl@{{ domain }} --header 'Subject: Test Mail - Unauthenticated and In-Network' --attach /tmp/eicar"
  changed_when: false

- name: Verify that Virus was Quarantined
  shell: "/usr/bin/find /var/lib/amavis/virusmails/ -name \"virus-*\" -print | /usr/bin/wc --lines"
  become: true
  register: shell_find_virus_count
  failed_when: (shell_find_virus_count.stdout | int) < 1
  changed_when: false

